<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<div class="row">
    <h3>Novo País</h3>
    <div class="col-lg-2">        
        <h5>DADOS DO PAÍS</h5>
        <?php echo $this->formPais; ?>
    </div>
    <div class="col-lg-10">
        <h5>PAÍSES CADASTRADAS</h5>
        <div class="table-responsive">
            <table class=" table table-bordered">
                <tr>
                    <th>ID</th>
                    <th>País</th>
                    <th>Continente</th>
                    <th>Confederação</th>
                    <th>Ação</th>
                </tr>
                <?php foreach ($this->paises as $pais) : ?>
                <tr>
                    <td><?php echo $pais->id_pais; ?></td>
                    <td><?php echo $pais->nome_pais; ?></td>
                    <td><?php echo $pais->continente_pais; ?></td>
                    <td><?php echo $pais->federacao; ?></td>
                    <td></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>