<div id="default-index-index">
    <div class="container">
        <div class="col-lg-12">
            <h4>CADASTROS</h4>
            <ul>
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'partidas',
                    'action' => 'nova-partida'
                )); ?>">Partida</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'resultados',
                    'action' => 'index'
                )); ?>">Resultado</a></li>                
            </ul>
        </div>
    </div>
</div>