<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<head>
    <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/admin/equipes/equipes.js'); ?>"></script> 
</head>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">Nova Equipe</div>
            <div class="panel-body">
                <?php echo $this->formEquipe; ?>
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">Equipes</div>
            <div class="panel-body">
                <div class="col-lg-12" style="margin: 5px 0;">
                    <input class="form-control form-horizontal" type="text" name="busca_equipe" id="busca_equipe" placeholder="Buscar Equipe" />
                </div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <?php foreach ($this->letras as $key => $letra) : ?>                                        
                    <?php $active = $key == 0 ? 'active' : ''; ?>
                    <li class="<?php echo $active; ?>">
                        <a id="<?php echo $letra->letras; ?>" class="aba_equipe" href="#<?php echo $letra->letras; ?>" role="tab" data-toggle="tab">                            
                            <?php echo $letra->letras; ?>
                        </a>
                    </li>
                    <?php endforeach; ?>                    
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <?php foreach ($this->letras as $key => $letra) : ?>                    
                    <?php $active = $key == 0 ? 'active' : ''; ?>                    
                    <div class="tab-pane fade <?php echo $active; ?> in" id="<?php echo $letra->letras; ?>">
                        <div class="col-lg-12">                            
                            <div id="table_equipes"></div>      
                        </div>
                    </div>
                    <?php endforeach; ?>                                        
                </div>
            </div>
        </div>
    </div>
</div>
