<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<h3>Novo Campeonato</h3>
<?php echo $this->formCampeonato; ?>
<div class="row">
    <div class="col-lg-12">
        <h5>CAMPEONATOS CADASTRADOS</h5>
        <div class="table-responsive">
            <table class=" table table-bordered">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Reputação</th>
                    <th>Ação</th>
                </tr>
                <?php foreach ($this->campeonato as $campeonato) : ?>
                    <tr>
                        <td><?php echo $campeonato->id_campeonato; ?></td>
                        <td><?php echo $campeonato->nome_campeonato; ?></td>
                        <td><?php echo $campeonato->descricao_campeonato; ?></td>
                        <td><?php echo $campeonato->descricao_reputacao; ?></td>
                        <td>
                            <a href="<?php echo $this->url(array(
                                'module' => 'admin',
                                'controller' => 'campeonatos',
                                'action' => 'nova-temporada',
                                'id' => $campeonato->id_campeonato                                
                            )); ?>">Temporada</a>
                        </td>                                                
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
