<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<h3>Grupo Equipe</h3>
<?php echo $this->formGrupoEquipe; ?>
<div class="row">
    <div class="col-lg-12">
        <a href="<?php echo $this->url(array(
            'module' => 'admin', 
            'controller' => 'campeonatos',
            'action' => 'novo-campeonato'
        ), null, true); ?>">Campeonatos</a> | 
        <a href="<?php echo $this->url(array(
            'module' => 'admin', 
            'controller' => 'campeonatos',
            'action' => 'nova-temporada',
            'id' => $this->id_campeonato
        ), null, true); ?>">Temporadas</a> |
        <a href="<?php echo $this->url(array(
            'module' => 'admin', 
            'controller' => 'campeonatos',
            'action' => 'nova-fase-campeonato',
            'id' => $this->id_fase_campeonato,
            'id_campeonato' => $this->id_campeonato
        ), null, true); ?>">Fases</a> | 
        <a href="<?php echo $this->url(array(
            'module' => 'admin', 
            'controller' => 'campeonatos',
            'action' => 'novo-grupo',
            'id' => $this->id_fase_campeonato,
            'id_campeonato' => $this->id_campeonato
        ), null, true); ?>">Grupos</a>
        <h5>EQUIPES DO GRUPO</h5>
        <div class="table-responsive">
            <table class=" table table-bordered">
                <tr>
                    <th>Equipe</th>
                    <th>Estádio</th>
                    <th>País</th>
                    <th colspan="2">Ações</th>
                </tr>
                <?php foreach ($this->equipes as $equipe) : ?>
                <tr>
                    <td>
                        <?php echo $equipe->nome_equipe; ?>
                        <?php if ($equipe->jogador) : ?>
                        <span style="font-size: 9px;"><?php echo '( ' . $equipe->jogador . ' )'; ?></span>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $equipe->apelido_estadio; ?></td>
                    <td><?php echo $equipe->nome_pais; ?></td>
                    <td>
                        <a href="<?php echo $this->url(array(
                            'module' => 'admin',
                            'controller' => 'campeonatos',
                            'action' => 'editar-equipe-grupo',
                            'id_grupo' => $equipe->id_grupo,
                            'id_equipe' => $equipe->id_equipe,
                            'id_campeonato' => $this->id_campeonato,
                            'id_fase_campeonato' => $this->id_fase_campeonato
                        )); ?>">Editar</a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array(
                            'module' => 'admin',
                            'controller' => 'campeonatos',
                            'action' => 'excluir-equipe-grupo',
                            'id_grupo' => $equipe->id_grupo,
                            'id_equipe' => $equipe->id_equipe,
                            'id_campeonato' => $this->id_campeonato,
                            'id_fase_campeonato' => $this->id_fase_campeonato
                        )); ?>">Excluir</a>
                    </td>                    
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>