<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<div class="row">
    <h3>Nova Cidade</h3>
    <div class="col-lg-2">
        <h5>DADOS DA CIDADE</h5>
        <?php echo $this->formCidade; ?>
    </div>
    <div class="col-lg-10">        
        <div class="table-responsive">
            <h5>CIDADES CADASTRADAS</h5>
            <table class=" table table-bordered">
                <tr>
                    <th>ID</th>
                    <th>País</th>
                    <th>Estado</th>
                    <th>Cidade</th>                    
                    <th>Ação</th>
                </tr>
                <?php foreach ($this->cidades as $cidade) : ?>
                <tr>
                    <td><?php echo $cidade->id_cidade; ?></td>
                    <td><?php echo $cidade->nome_pais; ?></td>
                    <td><?php echo $cidade->nome_estado; ?></td>
                    <td><?php echo $cidade->nome_cidade; ?></td>
                    <td></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
