<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-success">Jogos de Ontem <span class="badge"><?php echo $this->partidasOntem->count(); ?></span></div>
        <table class="table table-bordered small">
            <?php if ($this->partidasOntem->count() > 0) : ?>
            <?php foreach ($this->partidasOntem as $partida) : ?>            
            <tr class="text-center">
                <td class="col-lg-1 text-muted small">
                    <?php echo View_Helper_Date::date($partida->data_partida. ' ' .$partida->horario_partida, Zend_Date::TIME_SHORT); ?>h
                </td>
                <td class="col-lg-3">
                    <p><span class="text-muted small"><?php echo $partida->descricao_campeonato; ?></span></p> 
                    <span class="text-muted small"><?php echo $partida->apelido_estadio; ?></span> 
                </td>                       
                <td class="text-left col-lg-3">
                    <?php if ($partida->escudo_mandante) : ?>
                    <img class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_mandante); ?>" />
                    <?php endif; ?>
                    <?php echo $partida->mandante; ?>
                </td>
                <?php if ($partida->placar_equipe_mandante == $partida->placar_equipe_visitante && $partida->realizada && $partida->tipo_fase == 2) : ?>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_mandante; ?>
                        <p style="font-style: italic; font-size: 11px;">
                            <?php echo 'PR (' . $partida->placar_pr_mandante . ')'; ?>
                            <?php if ($partida->placar_pr_mandante == $partida->placar_pr_visitante) : ?>
                            <?php echo 'PK (' . $partida->placar_pk_mandante . ')'; ?>
                            <?php endif; ?>
                        </p>
                    </td>
                    <td class="col-lg-1"> X </td>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_visitante; ?>
                        <p style="font-style: italic; font-size: 11px;">
                            <?php echo 'PR (' . $partida->placar_pr_visitante . ')'; ?>                            
                            <?php if ($partida->placar_pr_mandante == $partida->placar_pr_visitante) : ?>
                            <?php echo 'PK (' . $partida->placar_pk_visitante . ')'; ?>
                            <?php endif; ?>
                        </p>
                    </td>
                <?php else : ?>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_mandante; ?>
                    </td>
                    <td class="col-lg-1"> X </td>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_visitante; ?>
                    </td>
                <?php endif; ?>
                <td class="text-right col-lg-3">
                    <?php echo $partida->visitante; ?>
                    <?php if ($partida->escudo_visitante) : ?>
                    <img class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_visitante); ?>" />
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php else : ?>
            <tr>
                <td>Nenhum jogo ontem</td>
            </tr>
            <?php endif; ?>
        </table>
        <div class="alert alert-success">Jogos de Hoje <span class="badge"><?php echo $this->partidasHoje->count(); ?></span></div>
        <table class="table table-bordered small">
            <?php if ($this->partidasHoje->count() > 0) : ?>
            <?php foreach ($this->partidasHoje as $partida) : ?>            
            <tr class="text-center">
                <td class="col-lg-1 text-muted small">
                    <?php echo View_Helper_Date::date($partida->data_partida. ' ' .$partida->horario_partida, Zend_Date::TIME_SHORT); ?>h
                </td>
                <td class="col-lg-3">
                    <p><span class="text-muted small"><?php echo $partida->descricao_campeonato; ?></span></p> 
                    <span class="text-muted small"><?php echo $partida->apelido_estadio; ?></span> 
                </td>       
                <td class="text-left col-lg-3">
                    <?php if ($partida->escudo_mandante) : ?>
                    <img class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_mandante); ?>" />
                    <?php endif; ?>
                    <?php echo $partida->mandante; ?>
                </td>
                <?php if ($partida->placar_equipe_mandante == $partida->placar_equipe_visitante && $partida->realizada) : ?>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_mandante; ?>
                        <p style="font-style: italic; font-size: 11px;">
                            <?php echo 'PR (' . $partida->placar_pr_mandante . ')'; ?>
                            <?php if ($partida->placar_pr_mandante == $partida->placar_pr_visitante) : ?>
                            <?php echo 'PK (' . $partida->placar_pk_mandante . ')'; ?>
                            <?php endif; ?>
                        </p>
                    </td>
                    <td class="col-lg-1"> X </td>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_visitante; ?>
                        <p style="font-style: italic; font-size: 11px;">
                            <?php echo 'PR (' . $partida->placar_pr_visitante . ')'; ?>                            
                            <?php if ($partida->placar_pr_mandante == $partida->placar_pr_visitante) : ?>
                            <?php echo 'PK (' . $partida->placar_pk_visitante . ')'; ?>
                            <?php endif; ?>
                        </p>
                    </td>
                    <?php else : ?>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_mandante; ?>
                    </td>
                    <td class="col-lg-1"> X </td>
                    <td class="col-lg-1">
                        <?php echo $partida->placar_equipe_visitante; ?>
                    </td>
                <?php endif; ?>
                <td class="text-right col-lg-3">
                    <?php echo $partida->visitante; ?>
                    <?php if ($partida->escudo_visitante) : ?>
                    <img class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_visitante); ?>" />
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php else : ?>
            <tr>
                <td>Nenhum jogo hoje</td>
            </tr>
            <?php endif; ?>
        </table>
        <div class="alert alert-success">Jogos de Amanhã <span class="badge"><?php echo $this->partidasAmanha->count(); ?></span></div>
        <table class="table table-bordered small">
            <?php if ($this->partidasAmanha->count() > 0) : ?>
            <?php foreach ($this->partidasAmanha as $partida) : ?>            
            <tr class="text-center">
                <td class="col-lg-1 text-muted small">
                    <?php echo View_Helper_Date::date($partida->data_partida. ' ' .$partida->horario_partida, Zend_Date::TIME_SHORT); ?>h
                </td>
                <td class="col-lg-3">
                    <p><span class="text-muted small"><?php echo $partida->descricao_campeonato; ?></span></p> 
                    <span class="text-muted small"><?php echo $partida->apelido_estadio; ?></span> 
                </td>                                
                <td class="text-left col-lg-3">
                    <?php if ($partida->escudo_mandante) : ?>
                    <img class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_mandante); ?>" />
                    <?php endif; ?>
                    <?php echo $partida->mandante; ?>
                </td>                
                <td> X </td>                
                <td class="text-right col-lg-3">
                    <?php echo $partida->visitante; ?>
                    <?php if ($partida->escudo_visitante) : ?>
                    <img class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_visitante); ?>" />
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php else : ?>
            <tr>
                <td>Nenhum jogo amanhã</td>
            </tr>
            <?php endif; ?>
        </table>
    </div>
</div>