<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<head>
    <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/admin/campeao/index.js'); ?>"></script> 
</head>
<div class="row">
    <h3>Novo Campeão</h3>
    <div class="col-lg-3">
        <h5>DADOS CAMPEÃO</h5>
        <?php echo $this->formCampeoes; ?>
    </div>
    <div class="col-lg-9">
        <h5>CAMPEÕES CADASTRADOS</h5>
        <table class="table table-bordered">
            <tr>
                <th>Campeonato</th>
                <th>Temporada</th>
                <th>Campeoão</th>
                <th>Ações</th>
            </tr>
            <?php if ($this->campeoes->count() > 0) : ?>
            <?php foreach ($this->campeoes as $campeao) : ?>
            <tr>
                <td><?php echo $campeao->descricao_campeoanto; ?></td>
                <td><?php echo $campeao->ano_temporada; ?></td>
                <td><?php echo $campeao->nome_equipe; ?></td>
            </tr>
            <?php endforeach; ?>
            <?php else : ?>
            <tr>
                <td colspan="4">Nenhum campeão cadastrado</td>
            </tr>
            <?php endif; ?>
        </table>           
    </div>
</div>