<div id="default-index-index">
    <div class="container">
        <h4>CADASTROS</h4>
        <div class="col-lg-4">                        
            <ul>
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'campeonatos',
                    'action' => 'novo-campeonato'
                )); ?>">Campeonatos</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'partidas',
                    'action' => 'nova-partida'
                )); ?>">Partida</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'resultados',
                    'action' => 'index'
                )); ?>">Resultado</a></li>                
            </ul>
        </div>
        <div class="col-lg-4">            
            <ul>
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'pais',
                    'action' => 'novo-pais'
                )); ?>">País</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'estado',
                    'action' => 'novo-estado'
                )); ?>">Estado</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'cidades',
                    'action' => 'nova-cidade'
                )); ?>">Cidade</a></li>                
            </ul>
        </div>
        <div class="col-lg-4">            
            <ul>
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'estadios',
                    'action' => 'novo-estadio'
                )); ?>">Estádio</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'equipes',
                    'action' => 'nova-equipe'
                )); ?>">Equipe</a></li>                                
            </ul>
        </div>
    </div>
</div>