<div id="default-index-index">
    <div class="navbar navbar-default background-color-blue">
        <div class="collapse navbar-collapse">                  
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'campeonatos',
                    'action' => 'novo-campeonato'
                ), null, true); ?>">Campeonatos</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'partidas',
                    'action' => 'nova-partida'
                ), null, true); ?>">Partida</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'resultados',
                    'action' => 'index'
                ), null, true); ?>">Resultado</a></li>      
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'campeoes',
                    'action' => 'index'
                ), null, true); ?>">Campeões</a></li>                  
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'pais',
                    'action' => 'novo-pais'
                ), null, true); ?>">País</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'estado',
                    'action' => 'novo-estado'
                ), null, true); ?>">Estado</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'cidades',
                    'action' => 'nova-cidade'
                ), null, true); ?>">Cidade</a></li>                            
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'estadios',
                    'action' => 'novo-estadio'
                ), null, true); ?>">Estádio</a></li>                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'equipes',
                    'action' => 'nova-equipe'
                ), null, true); ?>">Equipe</a></li>                                
                <li><a href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'reputacao',
                    'action' => 'nova-reputacao'
                ), null, true); ?>">Reputação</a></li>                              
            </ul>
        </div>
    </div>
</div>