<head>
    <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/default/campeonatos/index.js'); ?>"></script> 
</head>
<div id="<?php echo 'rodada_grupo_' . $this->id_grupo; ?>">
    <table class="table table-bordered">
        <tr>
            <th colspan="5">
                <?php $rodadas = View_Helper_Partida::getRodadasCampeonatoTemporada($this->id_temporada, $this->id_grupo); ?>                            
                <div style="float: left; width: 45%;">
                    <?php echo $this->dadosGrupo->descricao_grupo; ?>
                </div>                           
                <?php if ($rodadas <= 6) : ?>
                <div class="small text-center">
                    <?php for ($i = 1; $i <= $rodadas; $i++) : ?>
                    <a id="rodada_prev" href="javascript:void(0);" style="padding: 0 10px;" onclick="buscaRodada(
                        <?php echo $this->id_campeonato; ?>,
                        <?php echo $this->id_temporada; ?>,
                        <?php echo $this->id_grupo; ?>,
                        <?php echo $i; ?>
                    );"><?php echo $i; ?></a>
                    <?php endfor; ?>
                </div>
                <?php else : ?>
                <div style="float: right; width: 30%; text-align: center">
                    <input type="hidden" name="id_campeonato" id="id_campeonato" value="<?php echo $this->id_campeonato; ?>" />
                    <input type="hidden" name="id_temporada" id="id_temporada" value="<?php echo $this->id_temporada; ?>" />
                    <input type="hidden" name="id_grupo" id="id_grupo" value="<?php echo $this->id_grupo; ?>" />
                    <select name="rodada_select" id="rodada_select">
                    <?php for ($i = 1; $i <= $rodadas; $i++) : ?>                        
                    <option value="<?php echo $i; ?>" <?php echo $this->rodada == $i ? 'selected' : ''; ?>>Rodada <?php echo $i; ?></option>                        
                    <?php endfor; ?>
                </select>
                </div>
                <?php endif; ?>
            </th>
        </tr>
        <?php foreach ($this->partidas as $partida) : ?>            
            <tr>
                <td style="font-size: 10px;" class="text-muted small text-left" colspan="5">                                                    
                    <?php if ($partida->adiada) : ?>
                    <span class="text-danger">JOGO ADIADO</span>
                    <?php else : ?>
                    <?php echo $partida->data_partida ? ucfirst(View_Helper_Date::date($partida->data_partida, Zend_Date::WEEKDAY_NAME)) . ' - ' : ''; ?>
                    <?php echo $partida->data_partida ? View_Helper_Date::date($partida->data_partida, Zend_Date::DATE_SHORT) . ' - ' : ''; ?>
                    <?php echo $partida->horario_partida ? $partida->horario_partida . ' | ' : ''; ?> 
                    <?php echo $partida->apelido_estadio; ?>
                    <?php endif; ?>
                </td>
            </tr>
            <tr style="font-size: 11px;" class="text-center">                      
                <td class="text-right">
                    <?php if ($partida->escudo_mandante) : ?>
                    <img class="img-thumbnail" style="float: left; width: 45px; padding: 0 5px;" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_mandante); ?>" />
                    <?php else : ?>
                    <img style="float: left; width: 25px; padding: 0 5px;" class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/no.png'); ?>" />
                    <?php endif; ?>
                    <?php echo $partida->mandante; ?>
                </td>
                <td><b><?php echo $partida->placar_equipe_mandante !== null ? $partida->placar_equipe_mandante : '-'; ?></b></td>
                <td>X</td>
                <td><b><?php echo $partida->placar_equipe_visitante !== null ? $partida->placar_equipe_visitante : '-'; ?></b></td>
                <td class="text-left">
                    <?php echo $partida->visitante; ?>
                    <?php if ($partida->escudo_visitante) : ?>
                    <img class="img-thumbnail" style="float: right; width: 45px; padding: 0 5px;" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_visitante); ?>" />
                    <?php else : ?>
                    <img style="float: right; width: 25px; padding: 0 5px;" class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/no.png'); ?>" />
                    <?php endif; ?>
                </td>                
            </tr>

        <?php endforeach; ?>
    </table>
</div>