<h3><?php echo $this->nome_campeonato; ?></h3>
<div class="col-lg-2">
    <?php if ($this->fase_anterior) : ?>
    <a href="<?php echo $this->url(array(
        'module' => 'default',
        'controller' => 'campeonatos',
        'campeonato' => $this->id_campeonato,
        'temporada' => $this->id_temporada,
        'id_fase_campeonato' => $this->fase_anterior
    ), null, true); ?>"><h4>< Fase anterior</h4></a>
    <?php else : ?>
    <h4>< Fase anterior</h4>
    <?php endif; ?>
</div>
<div class="col-lg-8 text-center">
    <h4><?php echo $this->faseCampeonato->descricao_fase; ?></h4>
</div>
<div class="col-lg-2">
    <?php if ($this->fase_seguinte) : ?>
    <a href="<?php echo $this->url(array(
        'module' => 'default',
        'controller' => 'campeonatos',
        'campeonato' => $this->id_campeonato,
        'temporada' => $this->id_temporada,
        'id_fase_campeonato' => $this->fase_seguinte
    ), null, true); ?>"><h4>Fase seguinte ></h4></a>
    <?php else : ?>
    <h4>Fase seguinte ></h4>
    <?php endif; ?>
</div>    
<div class="row">
    <?php if ($this->faseCampeonato->tipo_fase == 1) : ?>
    <div class="col-lg-8">
        <h5>Grupos</h5>        
        <?php foreach ($this->grupos as $grupo) : ?>
        <table class="table table-bordered">
            <tr>
                <th colspan="10" class="center"><?php echo $grupo->descricao_grupo; ?></th>
            </tr>
            <tr>
                <th>Equipe</th>
                <th>Pts</th>
                <th>J</th>
                <th>V</th>
                <th>E</th>
                <th>D</th>
                <th>GF</th>
                <th>GC</th>
                <th>SG</th>
                <th>Apr (%)</th>
            </tr>
            <?php $tabela = View_Helper_Tabela::getTabelaGrupo($grupo->id_grupo, $grupo->id_fase_campeonato); ?>
            <?php foreach ($tabela as $equipe) : ?>
            <tr class="text-center">
                <td class="text-left">
                    <?php if ($equipe->escudo_equipe) : ?>
                    <img style="width: 25px;" class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/' . $equipe->escudo_equipe); ?>" />
                    <?php else : ?>
                    <img style="width: 25px;" class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/no.png'); ?>" />
                    <?php endif; ?>
                    <?php echo $equipe->nome_equipe; ?>
                    <?php if ($equipe->jogador) : ?>
                    <span style="font-size: 9px;"><?php echo '( ' . $equipe->jogador . ' )'; ?></span>
                    <?php endif; ?>
                </td>
                <td><?php echo ($equipe->vitorias * 3) + $equipe->empates; ?></td>
                <td><?php echo $equipe->jogos; ?></td>
                <td><?php echo $equipe->vitorias; ?></td>
                <td><?php echo $equipe->empates; ?></td>
                <td><?php echo $equipe->derrotas; ?></td>
                <td><?php echo $equipe->gols_pro; ?></td>
                <td><?php echo $equipe->gols_contra; ?></td>
                <td><?php echo $equipe->gols_pro - $equipe->gols_contra; ?></td>
                <td>X %</td>
            </tr>
            <?php endforeach; ?>
            <tr>
                <th colspan="10">&nbsp;</th>
            </tr>
        </table>
        <?php endforeach; ?>
        
    </div>
    <div class="col-lg-4">
        <h5>Rodadas</h5>
        <?php foreach ($this->grupos as $grupo) : ?>
        <table class="table table-bordered">
            <tr>
                <th colspan="5"><?php echo $grupo->descricao_grupo; ?></th>
            </tr>
            <?php $partidas = View_Helper_Partida::getRodadas($this->id_campeonato, $this->id_temporada, $grupo->id_grupo); ?>
            <?php foreach ($partidas as $partida) : ?>            
            <tr>
                <td style="font-size: 10px;" class="text-muted small text-left" colspan="5">
                    <?php echo $partida->rodada_partida; ?>ª rodada | 
                    <?php echo $partida->data_partida ? $partida->data_partida . ' - ' : ''; ?>
                    <?php echo $partida->horario_partida ? $partida->horario_partida . ' | ' : ''; ?> 
                    <?php echo $partida->apelido_estadio; ?>
                </td>
            </tr>
            <tr style="font-size: 11px;" class="text-center">                      
                <td class="text-right">
                    <?php if ($partida->escudo_mandante) : ?>
                    <img class="img-thumbnail" style="float: left; width: 25px; padding: 0 5px;" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_mandante); ?>" />
                    <?php else : ?>
                    <img style="float: left; width: 25px; padding: 0 5px;" class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/no.png'); ?>" />
                    <?php endif; ?>
                    <?php echo $partida->mandante; ?>
                </td>
                <td><b><?php echo $partida->placar_equipe_mandante !== null ? $partida->placar_equipe_mandante : '-'; ?></b></td>
                <td>X</td>
                <td><b><?php echo $partida->placar_equipe_visitante !== null ? $partida->placar_equipe_visitante : '-'; ?></b></td>
                <td class="text-left">
                    <?php echo $partida->visitante; ?>
                    <?php if ($partida->escudo_visitante) : ?>
                    <img class="img-thumbnail" style="float: right; width: 25px; padding: 0 5px;" src="<?php echo $this->baseUrl('views/img/escudos/' . $partida->escudo_visitante); ?>" />
                    <?php else : ?>
                    <img style="float: right; width: 25px; padding: 0 5px;" class="img-thumbnail" src="<?php echo $this->baseUrl('views/img/escudos/no.png'); ?>" />
                    <?php endif; ?>
                </td>                
            </tr> 
            <?php endforeach; ?>
        </table>
        <?php endforeach; ?>
    </div>
    <?php else : ?>
    <div class="col-lg-12">
        <h5>Jogos</h5>
        <?php foreach ($this->grupos as $grupo) : ?>
        <?php $jogo = View_Helper_Tabela::getJogosMataMata($grupo->id_grupo, $grupo->id_fase_campeonato); ?>        
        <table class="table table-bordered">
            <tr>
                <td><?php echo $grupo->descricao_grupo; ?></td>
                <td><?php echo $jogo[0]->nome_equipe; ?></td>
                <td>&nbsp;</td>
                <td> X </td>
                <td>&nbsp;</td>
                <td><?php echo $jogo[1]->nome_equipe; ?></td>
            </tr>            
        </table>
        <?php endforeach; ?>            
    </div>
    <?php endif; ?>
</div>

