<table class="table table-bordered">
    <tr>
        <th>Data</th>
        <th>Horário</th>
        <th>Estádio</th>
        <th>Mandante</th>
        <th colspan="3">&nbsp;</th>
        <th>Visitante</th>
        <th>Ações</th>
    </tr>
    <?php foreach ($this->partidas as $partida) : ?>
    <tr>
        <td><?php echo $partida->data_partida; ?></td>
        <td><?php echo $partida->horario_partida; ?></td>
        <td><?php echo $partida->apelido_estadio; ?></td>
        <td><?php echo $partida->mandante; ?></td>
        <td><?php echo $partida->placar_equipe_mandante; ?></td>
        <td> X </td>
        <td><?php echo $partida->placar_equipe_visitante; ?></td>
        <td><?php echo $partida->visitante; ?></td>
        <td>
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'partidas',
                'action' => 'editar-partida',
                'id_partida' => $partida->id_partida
            ), null, true); ?>">Editar</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>