<div class="row">
    <form method="post">  
    <h3>Editar Partida</h3>
    <div class="col-lg-5">                
            <table class="table">
                <tr>
                    <th colspan="8">Resultados</th>
                </tr>
                <tr>
                    <th>Tempo Normal: </th>
                    <td><?php echo $this->formResultado->placar_equipe_mandante; ?></td>
                    <td> X </td>
                    <td><?php echo $this->formResultado->placar_equipe_visitante; ?></td>
                </tr>
                <tr>
                    <th>Prorrogação: </th>
                    <td><?php echo $this->formResultado->placar_pr_mandante; ?></td>
                    <td> X </td>
                    <td><?php echo $this->formResultado->placar_pr_visitante; ?></td>
                </tr>
                <tr>
                    <th>Pênaltis: </th>
                    <td><?php echo $this->formResultado->placar_pk_mandante; ?></td>
                    <td> X </td>
                    <td><?php echo $this->formResultado->placar_pk_visitante; ?></td>
                </tr>
            </table>            
        </div>
        <div class="col-lg-7">
            <?php echo $this->formPartida; ?>
        </div>
    </form>
</div>
