<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<head>
    <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/admin/partidas/partidas.js'); ?>"></script> 
</head>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">Nova Partida</div>
            <div class="panel-body">
                <?php echo $this->formAdminPartida; ?>
                <div id="dados-campeonato"></div>
            </div>
        </div>        
    </div>
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">Partidas Cadastradas</div>
            <div class="panel-body">
                <div id="partidas-campeonato-temporada"></div>
            </div>
        </div>        
    </div>
</div>
