<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<div class="row">
    <h3>Novo Estado</h3>
    <div class="col-lg-2">
        <h5>DADOS DO ESTADO</h5>
        <?php echo $this->formEstado; ?>
    </div>
    <div class="col-lg-10">
        <h5>ESTADOS CADASTRADOS</h5>
        <div class="table-responsive">
            <table class=" table table-bordered">
                <tr>
                    <th>ID</th>
                    <th>País</th>
                    <th>Estado</th>
                    <th>Sigle</th>                    
                    <th>Ação</th>
                </tr>
                <?php foreach ($this->estados as $estado) : ?>
                <tr>
                    <td><?php echo $estado->id_estado; ?></td>
                    <td><?php echo $estado->nome_pais; ?></td>
                    <td><?php echo $estado->nome_estado; ?></td>
                    <td><?php echo $estado->sigla_estado; ?></td>                    
                    <td></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
