<div class="row">
    <div class="col-lg-12">
        <form action="<?php echo $this->formResultados->getAction(); ?>" method="post">    
            <?php echo $this->formResultados->id_partida; ?>
            <div class="">
                <dl class="dl-horizontal">
                    <dt>Campeonato:</dt>
                    <dd><?php echo $this->dadosPartida->nome_campeonato; ?></dd>
                    <dt>Fase Campeonato:</dt>
                    <dd>
                        <?php echo $this->dadosPartida->descricao_fase; ?>
                        <?php if ($this->dadosPartida->rodada_partida) : ?>
                        <span> - Rodada <?php echo $this->dadosPartida->rodada_partida; ?></span>
                        <?php endif; ?>
                    </dd>
                    <dt>Data/Horário:</dt>
                    <?php $data_hora = $this->dadosPartida->data_partida . ' ' . $this->dadosPartida->horario_partida; ?>
                    <dd><?php echo View_Helper_Date::date($data_hora, Zend_Date::DATETIME_SHORT); ?>h</dd>
                    <dt>Local:</dt>
                    <dd><?php echo $this->dadosPartida->apelido_estadio; ?></dd>
                </dl>
            </div>
            <table class="table table-responsive">               
                <tr class="text-center">
                    <td class="col-sm-2">                
                        <?php if ($this->dadosPartida->escudo_mandante) : ?>
                            <img src="<?php echo $this->baseUrl('views/img/escudos/' . $this->dadosPartida->escudo_mandante); ?>" class="img-thumbnail" width="45" />
                        <?php endif; ?>
                        <?php echo $this->dadosPartida->mandante; ?>
                    </td>
                    <td class="col-sm-1"><?php echo $this->formResultados->placar_equipe_mandante; ?></td>
                    <td class="col-sm-1">X</td>
                    <td class="col-sm-1"><?php echo $this->formResultados->placar_equipe_visitante; ?></td>
                    <td class="col-sm-2">
                        <?php echo $this->dadosPartida->visitante; ?>
                        <?php if ($this->dadosPartida->escudo_visitante) : ?>
                            <img src="<?php echo $this->baseUrl('views/img/escudos/' . $this->dadosPartida->escudo_visitante); ?>" class="img-thumbnail" width="45" />
                        <?php endif; ?>
                    </td>
                    <td class="col-sm-1"><?php echo $this->dadosPartida->tipo_fase == 1 ? $this->formResultados->submit : ''; ?></td>
                </tr>
                <?php if ($this->dadosPartida->tipo_fase == 2) : ?>
                    <tr class="text-center">
                        <th>Prorrogação</th>
                        <td><?php echo $this->formResultados->placar_pr_mandante; ?></td>
                        <td> X </td>
                        <td><?php echo $this->formResultados->placar_pr_visitante; ?></td>
                        <td colspan="3"></td>
                    </tr>
                    <tr class="text-center">
                        <th>Penaltes</th>
                        <td><?php echo $this->formResultados->placar_pk_mandante; ?></td>
                        <td> X </td>
                        <td><?php echo $this->formResultados->placar_pk_visitante; ?></td>
                        <td class="text-right"><?php echo $this->dadosPartida->tipo_fase == 2 ? $this->formResultados->submit : ''; ?></td>
                    </tr>
                <?php endif; ?>
            </table>
        </form>
    </div>
</div>