<head>
    <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/admin/resultados/resultados.js'); ?>"></script> 
</head>
<?php echo $this->partial('index/index.phtml'); ?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Resultados <span class="badge"><?php echo $this->partidasPendentes; ?></span></div>
            <div class="panel-body">
                <?php echo $this->formResultados; ?>
                <div id="dados-campeonato"></div>
            </div>
        </div>
    </div>
</div>
