<?php echo $this->partial('partials/menu-admin.phtml'); ?>
<div class="row">
    <h3>Nova Reputação</h3>
    <div class="col-lg-2">
        <h5>DADOS REPUTAÇÃO</h5>
        <?php echo $this->formReputacao; ?>
    </div>
    <div class="col-lg-10">
        <h5>REPUTAÇÕES CADASTRADAS</h5>
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <th>Reputação</th>
                <th>Ordem</th>
                <th colspan="2">Ações</th>
            </tr>
            <?php foreach ($this->reputacoes as $reputacao) : ?>
            <tr>
                <td><?php echo $reputacao->id_reputacao; ?></td>
                <td><?php echo $reputacao->descricao_reputacao; ?></td>
                <td><?php echo $reputacao->ordem; ?></td>
                <td>
                    <a href="">Editar</a>
                </td>
                <td>
                    <a href="<?php echo $this->url(array(
                        'module' => 'admin',
                        'controller' => 'reputacao',
                        'action' => 'excluir-reputacao',
                        'id_reputacao' => $reputacao->id_reputacao
                    )); ?>">Excluir</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>