<html>
    <head>
        <?php header('Content-Type: text/html; charset=UTF-8'); ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/jquery-2.0.3.js'); ?>"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/jquery-ui-1.10.3.js'); ?>"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/jquery.ui.datepicker-pt-BR.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/jquery.maskedinput.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('views/js/functions.js'); ?>"></script> 
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('views/css/bootstrap/bootstrap.css'); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('views/css/bootstrap/bootstrap-theme.css'); ?>" />
    </head>
    <body>        
        <div class="container-fluid">            
            <div class="row">
                <div class="col-lg-2 small">                    
                    <ul class="list-group-item">
                        <?php foreach ($this->campeonatos as $reputacao) : ?>
                            <li class="list-inline">
                                <div class="well-sm bg-success"><b><?php echo $reputacao['descricao_reputacao']; ?></b></div>
                            </li>
                            <ul class="">
                                <?php foreach ($reputacao['campeonatos'] as $campeonato) : ?>
                                    <?php
                                        $class = $campeonato['finalizado'] ? 'text-danger' : 'text-info';
                                    ?>
                                    <li style="margin-left: -30px;" class="list-inline">
                                        <a class="<?php echo $class; ?>" href="<?php echo $this->url(array(
                                                'module' => 'default',
                                                'controller' => 'campeonatos',
                                                'action' => 'index',
                                                'campeonato' => $campeonato['id_campeonato'],
                                                'temporada' => $campeonato['id_campeonato_temporada']
                                            ), null, true); ?>">
                                            <?php echo $campeonato['nome_campeonato'] . ' ' . $campeonato['ano_temporada']; ?>                                            
                                        </a>
                                    </li>
                                    <hr style="margin: 5px 0; "/>
                                <?php endforeach; ?>                                
                            </ul>
                        <?php endforeach; ?>
                        <hr />
                    </ul>                    
                </div>
                <div class="col-lg-10">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>